const nodemailer = require('nodemailer');

async function sendEmail(options) {
    const mail = nodemailer.createTransport({
        service: options.emailService,
        auth: {
            user: options.user,
            pass: options.password,
        }
    });
    var mailOptions = {
        from: options.from,
        to: options.to,
        subject: `GPX ${(new Date()).toISOString()}`,
        text: 'Generated by SignalK Tracker',
        attachments: [{   // file on disk as an attachment
            filename: 'track.gpx',
            path: options.trackFile // stream this file
        }],
    };
    await mail.sendMail(mailOptions);
}

module.exports = sendEmail;